export { default as costosFijos } from './costosFijos'
export { default as costosVariables } from './costosVariables'
export { default as credito } from './credito'
export { default as ingresosVariables } from './ingresosVariables'
export { default as inversion } from './inversion'
